name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        run: terraform init && terraform apply -auto-approve

      - name: Generate .env for Frontend
        run: |
          echo "VITE_USER_POOL_ID=$(terraform output -raw user_pool_id)" > $GITHUB_WORKSPACE/frontend/.env
          echo "VITE_CLIENT_ID=$(terraform output -raw user_pool_client_id)" >> $GITHUB_WORKSPACE/frontend/.env
          echo "VITE_BASE_URL_ID=$(terraform output -raw base_url)" >> $GITHUB_WORKSPACE/frontend/.env

      - name: Debug .env File
        run: cat $GITHUB_WORKSPACE/frontend/.env

      - name: Upload .env to artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-env
          path: ${{ github.workspace }}/frontend/.env
