name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/terraform/**'
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        run: terraform init && terraform apply -auto-approve

      - name: Generate .env for Frontend
        run: |
          echo "VITE_USER_POOL_ID=$(terraform output -raw user_pool_id)" > ../../frontend/.env
          echo "VITE_CLIENT_ID=$(terraform output -raw user_pool_client_id)" >> ../../frontend/.env
          echo "VITE_BASE_URL_ID=$(terraform output -raw base_url)" >> ../../frontend/.env

      - name: Upload .env to artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-env
          path: frontend/.env
