name: Terraform Cleanup

on:
  workflow_dispatch:

jobs:
  terraform-cleanup:
    name: 'Post Apply Cleanup'
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: 'Checkout GitHub repository'
        uses: actions/checkout@v3

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: 'Terraform Init'
        run: terraform init
        
      - name: 'Terraform Plan Destroy'
        run: terraform plan -destroy -out=tfplan-destroy

      - name: 'Terraform Apply Destroy'
        run: terraform apply -auto-approve tfplan-destroy
