name: Destroy Backend Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Initialize Terraform
        working-directory: backend/terraform
        run: terraform init -backend-config="bucket=inventory-terraform-state-bucket" \
                             -backend-config="key=terraform.tfstate" \
                             -backend-config="region=ap-south-1" \
                             -backend-config="dynamodb_table=terraform-lock-table" \
                             -backend-config="encrypt=true"

      - name: Terraform Destroy
        working-directory: backend/terraform
        run: terraform destroy -auto-approve
