name: Destroy Backend Infrastructure

on:
  workflow_dispatch:
  # Optional: Auto-destroy on branch deletion
  # delete:
  #   branches:
  #     - feature/**

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Initialize Terraform
        working-directory: backend/terraform
        run: terraform init

      - name: Terraform Destroy
        working-directory: backend/terraform
        run: terraform destroy -auto-approve
