name: Backend Deploy (Terraform)

on:
  push:
    paths:
      - 'backend/terraform/**'
      - '.github/workflows/backend.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: backend/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: backend/terraform
        run: terraform apply -auto-approve

      - name: Extract Terraform Output
        id: tf_output
        working-directory: backend/terraform
        run: |
          terraform output -json > output.json
          echo "BASE_URL=$(jq -r '.base_url.value' output.json)" >> $GITHUB_ENV
          echo "USER_POOL_ID=$(jq -r '.user_pool_id.value' output.json)" >> $GITHUB_ENV
          echo "USER_POOL_CLIENT_ID=$(jq -r '.user_pool_client_id.value' output.json)" >> $GITHUB_ENV

      - name: Update Netlify Env Variables
        run: |
          curl -X PATCH https://api.netlify.com/api/v1/sites/${NETLIFY_SITE_ID} \
          -H "Authorization: Bearer ${NETLIFY_AUTH_TOKEN}" \
          -H "Content-Type: application/json" \
          --data '{
            "build_settings": {
              "env": {
                "VITE_API_BASE_URL": "'"${BASE_URL}"'",
                "VITE_COGNITO_USER_POOL_ID": "'"${USER_POOL_ID}"'",
                "VITE_COGNITO_CLIENT_ID": "'"${USER_POOL_CLIENT_ID}"'"
              }
            }
          }'
